resource_group_name     = "taskboard"
resource_group_location = "North Europe"
app_service_plan_name   = "task-board-plan"
app_service_name        = "taskboarddemoiliana"
sql_server_name         = "server"
sql_database_name       = "taskboard"
sql_admin_login         = "user01"
sql_admin_password      = "thisIsKat11"
firewall_rule_name      = "firewall"
repo_URL                = "https://github.com/ilianachakarova/taskboard"

